version: '3.7'

services:
#  postgres:
#    image: postgres:${POSTGRES_VERSION}
#    container_name: filedb
#    environment:
#      POSTGRES_USER: ${POSTGRES_USER}
#      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
#      POSTGRES_DB: ${POSTGRES_DB}
#    ports:
#      - "${POSTGRES_PORT}:5432"
#    volumes:
#      - postgres-data:/var/lib/postgresql/data

  minio:
    image: minio/minio:${MINIO_VERSION} # образ MinIO указанной версии.
    container_name: minio # Имя контейнера.
    restart: unless-stopped # Перезапускать, если контейнер был остановлен, кроме случаев, когда Docker демон был перезапущен.
    volumes: # Сопоставление локальных директорий с директориями в контейнере.
      - "./minio/data:/data"
      - "./minio/minio:/minio"
      - "./minio/config:/root/.minio"
    environment: # Установка переменных окружения.
      TZ: ${TZ}
      LANG: ${LANG}
      MINIO_PROMETHEUS_AUTH_TYPE: "public" # Тип аутентификации для Prometheus.
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
    command: server /data --console-address ":${MINIO_CONSOLE_PORT}" # Команда для запуска MinIO с указанием пути к данным и порта для доступа к консоли.
    logging:
      driver: "json-file" # Драйвер для логирования.
      options:
        max-size: "100m" # Максимальный размер лог-файла.
    ports: # Проброс портов.
      - "9000:9000" # Порт для загрузки и предварительного просмотра файлов.
      - "${MINIO_CONSOLE_PORT}:${MINIO_CONSOLE_PORT}" # Порт для доступа к консоли MinIO.

volumes:
#  postgres-data:
  minio-data:
