version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    restart: unless-stopped
    environment:
      MINIO_URL: http://minio:9000
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
      MINIO_BUCKET_NAME: ${MINIO_BUCKET_NAME}
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/ActiveDocksApp
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 123
      SALT_SECRET_KEY: ${SALT_SECRET_KEY}
    depends_on:
      - postgres
      - minio
    ports:
      - "8080:8080" # Порт, на котором работает ваше приложение
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ActiveDocksApp
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 123
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  minio:
    image: minio/minio:${MINIO_VERSION} # образ MinIO указанной версии.
    container_name: minio # Имя контейнера.
    restart: unless-stopped # Перезапускать, если контейнер был остановлен, кроме случаев, когда Docker демон был перезапущен.
    volumes: # Сопоставление локальных директорий с директориями в контейнере.
      - "./minio/data:/data"
      - "./minio/minio:/minio"
      - "./minio/config:/root/.minio"
    environment: # Установка переменных окружения.
      TZ: ${TZ}
      LANG: ${LANG}
      MINIO_PROMETHEUS_AUTH_TYPE: "public" # Тип аутентификации для Prometheus.
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
    command: server /data --console-address ":${MINIO_CONSOLE_PORT}" # Команда для запуска MinIO с указанием пути к данным и порта для доступа к консоли.
    logging:
      driver: "json-file" # Драйвер для логирования.
      options:
        max-size: "100m" # Максимальный размер лог-файла.
    ports: # Проброс портов.
      - "9000:9000" # Порт для загрузки и предварительного просмотра файлов.
      - "${MINIO_CONSOLE_PORT}:${MINIO_CONSOLE_PORT}" # Порт для доступа к консоли MinIO.

volumes:
  postgres-data:
  minio-data:
